version: '3.8'

services:
  chatapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatapp-container
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://109.199.102.40:4004
    volumes:
      # إضافة volumes للبيانات المستمرة إذا لزم الأمر
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge

# إضافة volumes للبيانات المستمرة
volumes:
  app-data:version: '3.8'