version: '3.8'

services:
  chatapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-chatapp-container
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://31.97.181.122:4004
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - souq_network

networks:
  souq_network:
    external: true

volumes:
  app-data:
